name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload ftp
      uses: GenieTim/ftp-action@v4.0.1
      with:
        host: ftpupload.net
        user: if0_37803392
        password: JyS6H9SWCaoFM
        remoteDir: "htdocs"
